from project_paths import POSE_MODEL_PATH, PROCESSED_DATASET_DIR, RAW_LABELED_VIDEOS_DIR

LABELED_VIDEO_PATH = RAW_LABELED_VIDEOS_DIR / "labeled-videos-2026-04-22-00-05-e3d836a2.csv"
DATASET_OUTPUT_PATH = PROCESSED_DATASET_DIR / "keypoints-labeled.csv"
MODEL_PATH = POSE_MODEL_PATH

DESIRED_COLUMNS = ["id", "choice", "video"]
NUM_FRAMES = 7
CSV_FIELDNAMES = ["choice", "id", "features", "status"]
DEFAULT_NUM_WORKERS = 2
